### ISSUE TITLE
Number and Elements don't match

### ISSUE THREAD

**Issue by mikeiit** [Griffintaur/Periodic2048#9]
Hi @Griffintaur, this looks great. I would like to contribute. First issue I found is the mismatch between the elements and the math in the game. Like 2 He tiles should be combined to 1 Be tile, but we get 1 C tile. Can you help explain the design of this part?

**Comment by Griffintaur** [comment]
I think it's maybe the bug in the code. It would be great if you could fix
it. As fas as I know 3 He atoms combine to form one carbon.
Please check on this and thanks for your willingness to help us out there.
I highly appreciate it.

**Comment by mikeiit** [comment]
Not a problem at all @Griffintaur, it seems that the underlying math of combining two tiles and calculating the score in this game, which is the same as how the original game 2048 works, doesn't match the way a reaction would. We can't match the tile value to any concept in a reaction. Like there is no way to explain how 2 HE form a C or how 2 C form a O. But this could be a game to help memorize the periodic table itself. If we just map the tile value to atomic number of an element, it will make sense. Like tile with value 4 stands for Be, and two of them combines to a O, which has atomic number 8. What do you think?

**Comment by Griffintaur** [comment]
I agree that what you proposed will surely help to memorize the periodic
table.
we can go on that route. I am ok with it.

**Comment by sakshivij** [comment]
Hi @Griffintaur I would love to contribute to this. Has the changes with the above mentioned Apporach made? If not I would like to work on it.

**Comment by mikeiit** [comment]
Hi @sakshivij I have made the change in my fork. Feel free to go check the code in my repository.

https://github.com/mikeiit/Periodic2048

Thanks :)

**Comment by sakshivij** [comment]
Oh okay. Thanks for letting me know :)

**Comment by Griffintaur** [comment]
@mikeiit can you send the PR so that changes can be merged

**Comment by mikeiit** [comment]
Hey @Griffintaur  I just sent out a PR. But I have been making changes in my repo as we discussed in PR #11 . Whatever change I made likely will not work with PR #12. Please take a close look if you want to merge. Thanks.

**Comment by Griffintaur** [comment]
@mikeiit  I understand. I will create another branch with your changes. so that it remains in sync with your work.

**Comment by Ishita036** [comment]
Is this issue still open? If so, I can take it.

**Comment by Griffintaur** [comment]
Yes
